In [1]:
import numpy as np

import sim

In [2]:
simulator = sim.Sim(200)

POSSIBLE_ACTIONS = simulator.POSSIBLE_ACTIONS

In [3]:
simulator.reset()
for _ in range(200):
    simulator.step(np.random.choice(POSSIBLE_ACTIONS))
    print()

[]
2
2
Road 1:  [<sim.Car object at 0x106d2ef90>]
Road 2:  [<sim.Car object at 0x1070260d0>]
Road 3:  []
Road 4:  []
[[[ 1.  0.  2.  1.  1.]]

 [[ 1.  0.  2.  1.  1.]]

 [[nan nan nan nan nan]]

 [[nan nan nan nan nan]]]

0
2
Road 1:  [<sim.Car object at 0x106d2ef90>, <sim.Car object at 0x106bf6a90>]
Road 2:  [<sim.Car object at 0x1070260d0>, <sim.Car object at 0x1070cfd90>]
Road 3:  []
Road 4:  []
[[[ 3.  0.  2.  2.  1.]
  [ 1.  0.  0.  1.  1.]]

 [[ 3.  0.  2.  2.  1.]
  [ 1.  0.  2.  1.  1.]]

 [[nan nan nan nan nan]
  [nan nan nan nan nan]]

 [[nan nan nan nan nan]
  [nan nan nan nan nan]]]

2
2
Road 1:  [<sim.Car object at 0x106d2ef90>, <sim.Car object at 0x106bf6a90>, <sim.Car object at 0x107025fd0>]
Road 2:  [<sim.Car object at 0x1070260d0>, <sim.Car object at 0x1070cfd90>]
Road 3:  [<sim.Car object at 0x1070dc110>]
Road 4:  []
[[[ 5.  0.  2.  2.  0.]
  [ 3.  0.  0.  2.  1.]
  [ 1.  0.  2.  1.  1.]]

 [[ 5.  0.  2.  2.  0.]
  [ 3.  0.  2.  2.  1.]
  [nan nan nan nan nan]]

 [[ 1